POST https://api-node-5cvl.onrender.com/videos
Content-Type: application/json

{
    "title": "Video teste",
    "description": "Horraaaable!",
    "duration": 550
}

###

GET https://api-node-5cvl.onrender.com/videos

### 

PUT https://api-node-5cvl.onrender.com/videos/cb502710-cf5a-4082-a75d-f0c7d359bdf2
Content-Type: application/json

{
    "title": "Car Mechanics Advice",
    "description": "cyka blyat ina hoy",
    "duration": 200
}


###

DELETE https://api-node-5cvl.onrender.com/videos/cb502710-cf5a-4082-a75d-f0c7d359bdf2